name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2

#      - name: Run sample script
#        run: echo "Hello from CI/CD"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew lintDebug

      - name: Upload HTML test report
        uses: actions/upload-artifact@v2
        with:
          name: lint-report.html
          path: app/build/reports/lint-results-debug.html